run:
  phase: action
  seed: 42
  work_dir: outputs

data:
  name: droid
  path: /path/to/droid
  fps: 12
  batch_size: 32
  num_workers: 8
  pin_memory: true
  shuffle: true

model:
  embed_dim: 256
  predictor:
    layers: 6
    heads: 4
  fuser:
    heads: 4
    drop: 0.1
  action:
    dim: 7
  freeze_encoder: true
  downsampler:
    enable_variable: true
    max_queries: 256
    ratio_pred_dim: 4
    ratio_mode: keep_frac
    gumbel_tau: 1.0
    hard_select: false
    ratio_target: 0.5
    ratio_loss_weight: 0.0

loss:
  energy:
    conditioned: true

train:
  epochs: 50
  lr: 0.0001
  weight_decay: 0.05
  cem_samples: 100
  alpha: 0.0
  compression_ratio: 0.5

dist:
  world_size: 1
  backend: nccl
  fp16: false

logging:
  interval: 50
