run:
  phase: probe
  seed: 42
  work_dir: outputs

data:
  name: ssv2_saliency
  path: /path/to/ssv2_with_saliency
  batch_size: 32
  num_workers: 8
  pin_memory: true
  shuffle: true

model:
  embed_dim: 256
  freeze_backbone: true
  downsampler:
    enable_variable: true
    max_queries: 256
    ratio_pred_dim: 4
    ratio_mode: keep_frac
    gumbel_tau: 1.0
    hard_select: false
    ratio_target: 0.5
    ratio_loss_weight: 0.0

loss:
  bce: {}
  energy:
    lambda: 0.1

train:
  epochs: 20
  lr: 0.0001
  weight_decay: 0.05
  alpha: 0.0
  compression_ratio: 0.5

dist:
  world_size: 1
  backend: nccl
  fp16: false

logging:
  interval: 50
