run:
  phase: probe
  seed: 42
  work_dir: outputs

data:
  name: ssv2_saliency
  path: /path/to/ssv2_with_saliency
  batch_size: 32
  num_workers: 8
  pin_memory: true
  shuffle: true

model:
  embed_dim: 256
  freeze_backbone: true

loss:
  bce: {}
  energy:
    lambda: 0.1

train:
  epochs: 20
  lr: 0.0001
  weight_decay: 0.05

dist:
  world_size: 1
  backend: nccl
  fp16: false

logging:
  interval: 50
