run:
  phase: ssl_refine
  seed: 42
  work_dir: outputs

data:
  name: ssv2_ssl
  path: /path/to/ssv2
  fps: 12
  batch_size: 64
  num_workers: 8
  pin_memory: true
  shuffle: true

model:
  embed_dim: 256
  predictor:
    layers: 6
    heads: 4

loss:
  vicregl:
    inv: 25.0
    var: 25.0
    cov: 1.0
  energy:
    robust_loss: huber

train:
  epochs: 100
  lr: 0.0001
  weight_decay: 0.05
  mask_ratio: 0.4
  lambda_vic: 1.0

dist:
  world_size: 1
  backend: nccl
  fp16: false

logging:
  interval: 50
